services:
  frontend:
    build: ./payme
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build: ./payme_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
